[package]
name = "andromeda-app"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { workspace = true }
andromeda-std = { workspace = true }
