version: "3"

services:
  localosmosis-a:
    build: 
      context: https://github.com/osmosis-labs/osmosis.git#main
      args:
        RUNNER_IMAGE: alpine:3.17
        GO_VERSION: "1.20"
    volumes:
      - ./scripts/setup_chain.sh:/osmosis/setup.sh
      - ./template/.osmosisd-local-a/:/osmosis/.osmosisd/
    entrypoint:
      - /osmosis/setup.sh
    environment:
      - CHAIN_ID=localosmosis-a
      - VALIDATOR_MONIKER=validator-a
      - VALIDATOR_MNEMONIC=family album bird seek tilt color pill danger message abuse manual tent almost ridge boost blast high comic core quantum spoon coconut oyster remove
      - FAUCET_MNEMONIC=notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius
      - RELAYER_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
    networks:
      - localosmosis

  localosmosis-b:
    build:
      context: https://github.com/osmosis-labs/osmosis.git#main
      args:
        RUNNER_IMAGE: alpine:3.17
        GO_VERSION: "1.20"
    volumes:
      - ./scripts/setup_chain.sh:/osmosis/setup.sh
      - ./template/.osmosisd-local-b:/osmosis/.osmosisd
    entrypoint:
      - /osmosis/setup.sh
    environment:
      - CHAIN_ID=localosmosis-b
      - VALIDATOR_MONIKER=validator-b
      - VALIDATOR_MNEMONIC=family album bird seek tilt color pill danger message abuse manual tent almost ridge boost blast high comic core quantum spoon coconut oyster remove
      - FAUCET_MNEMONIC=notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius
      - RELAYER_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      # Can't use the same ports
      - 36657:26657
      - 31317:1317
      - 39090:9090
    networks:
      - localosmosis
  hermes:
    image: informalsystems/hermes:1.1.0
    user: root:root
    volumes:
      - ./scripts/setup_hermes.sh:/home/hermes/setup.sh
      - ./config/hermes/config.toml:/root/.hermes/config.toml
    entrypoint:
      - /home/hermes/setup.sh
    environment:
      - CHAIN_A_ID=localosmosis-a
      - CHAIN_A_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
      - CHAIN_B_ID=localosmosis-b
      - CHAIN_B_MNEMONIC=black frequent sponsor nice claim rally hunt suit parent size stumble expire forest avocado mistake agree trend witness lounge shiver image smoke stool chicken
    ports:
      - 3000:3000
    depends_on:
      - localosmosis-a
      - localosmosis-b
    networks:
      - localosmosis

networks:
  localosmosis:
